### PR TITLE
Added V&A accession numbers patterns

### PR DESCRIPTION
**Pull request by sheharbano96**
We'd like to contribute the V&A accession number patterns to the project. We've executed the test-runner on the json and it has passed all the tests.

### CODE REVIEW

**Comment by thisisaaronland** [comment]
Thanks! 

I see that there are (3) different patterns but each has the same label (`common`). Would you assign each their own individual descriptive labels, please?

**Comment by sheharbano96** [comment]
No problem. I just updated the labels. I hope it's alright now.

**Comment by thisisaaronland** [comment]
Thanks again! The definition file should be `vam.ac.uk.json` (definition files correspond to the principal domain for an institution) but I will change that after the fact.

**Comment by sheharbano96** [comment]
Thanks, Appreciate it!

**Pull request merged**
